// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhjlrukwsdcmvvbncucy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoamxydWt3c2RjbXZ2Ym5jdWN5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MDI0NjQsImV4cCI6MjA2OTI3ODQ2NH0.M1UXve7yDoILZmt4r2yh7Ya6ONtJ_wCaoGIzAER6lp0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});